"""Initial schema

Revision ID: e029f1773f2e
Revises: 
Create Date: 2026-07-10 13:02:57.358791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e029f1773f2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_verification',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verification_email'), 'otp_verification', ['email'], unique=False)
    op.create_table('workspace',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('solo', 'firm', name='workspacetypeenum'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_user',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', name='roleenum'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_table('client',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_gstin'), 'client', ['gstin'], unique=True)
    op.create_table('subscription',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_allocation',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gstn_credential',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('encrypted_password', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliation_run',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='runstatusenum'), nullable=False),
    sa.Column('tax_period', sa.String(length=7), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploaded_file',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('purchase_register', 'gstr_2b', name='filekindenum'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('financial_year', sa.String(length=9), nullable=True),
    sa.Column('tax_period', sa.String(length=7), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('is_frequent', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_gstin'), 'vendor', ['gstin'], unique=False)
    op.create_table('portal_invoice',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_gstin', sa.String(length=15), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_number_norm', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cess', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_invoice_invoice_number_norm'), 'portal_invoice', ['invoice_number_norm'], unique=False)
    op.create_index(op.f('ix_portal_invoice_supplier_gstin'), 'portal_invoice', ['supplier_gstin'], unique=False)
    op.create_table('purchase_invoice',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_gstin', sa.String(length=15), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_number_norm', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cess', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_invoice_invoice_number_norm'), 'purchase_invoice', ['invoice_number_norm'], unique=False)
    op.create_index(op.f('ix_purchase_invoice_supplier_gstin'), 'purchase_invoice', ['supplier_gstin'], unique=False)
    op.create_table('match_result',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_invoice_id', sa.Uuid(), nullable=True),
    sa.Column('portal_invoice_id', sa.Uuid(), nullable=True),
    sa.Column('bucket', sa.Enum('matched', 'mismatched', 'missing_in_portal', 'missing_in_books', 'probable', name='bucketenum'), nullable=False),
    sa.Column('match_pass', sa.Enum('exact', 'normalized', 'tolerance', 'fuzzy', name='matchpassenum'), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_diff', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('review_status', sa.Enum('pending', 'confirmed', 'rejected', 'skipped', name='reviewstatusenum'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portal_invoice_id'], ['portal_invoice.id'], ),
    sa.ForeignKeyConstraint(['purchase_invoice_id'], ['purchase_invoice.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_result')
    op.drop_index(op.f('ix_purchase_invoice_supplier_gstin'), table_name='purchase_invoice')
    op.drop_index(op.f('ix_purchase_invoice_invoice_number_norm'), table_name='purchase_invoice')
    op.drop_table('purchase_invoice')
    op.drop_index(op.f('ix_portal_invoice_supplier_gstin'), table_name='portal_invoice')
    op.drop_index(op.f('ix_portal_invoice_invoice_number_norm'), table_name='portal_invoice')
    op.drop_table('portal_invoice')
    op.drop_index(op.f('ix_vendor_gstin'), table_name='vendor')
    op.drop_table('vendor')
    op.drop_table('uploaded_file')
    op.drop_table('reconciliation_run')
    op.drop_table('gstn_credential')
    op.drop_table('client_allocation')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_client_gstin'), table_name='client')
    op.drop_table('client')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_table('workspace')
    op.drop_index(op.f('ix_otp_verification_email'), table_name='otp_verification')
    op.drop_table('otp_verification')
    # ### end Alembic commands ###
