from typing import List, Dict, Any
from uuid import UUID

def run_matching_passes(pr_list: List[Dict[str, Any]], portal_list: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Interface: normalized PR list + 2B list -> MatchResult list.
    Runs Pass 1 (Exact) and Pass 2 (Normalized).
    """
    match_results = []
    
    # Track which portal (2B) invoices have already been claimed/matched
    matched_portal_ids = set()

    # --- PASS 1: EXACT MATCH ---
    # Look for perfectly identical rows based on GSTIN, Original Invoice Number, Date, and Tax.
    for pr in pr_list:
        found_match = None
        
        for tx2b in portal_list:
            if tx2b["id"] in matched_portal_ids:
                continue
                
            # Exact criteria match 
            if (pr["supplier_gstin"] == tx2b["supplier_gstin"] and
                pr["invoice_no"] == tx2b["invoice_no"] and
                pr["invoice_date"] == tx2b["invoice_date"] and
                abs(pr["total_tax"] - tx2b["total_tax"]) < 0.01):
                
                found_match = tx2b
                break
                
        if found_match:
            matched_portal_ids.add(found_match["id"])
            match_results.append({
                "workspace_id": pr["workspace_id"],
                "client_id": pr["client_id"],
                "run_id": pr["run_id"],
                "purchase_invoice_id": pr["id"],
                "portal_invoice_id": found_match["id"],
                "bucket": "Matched",
                "match_pass": "P1_Exact",
                "confidence": 100.0,
                "tax_diff": 0.0
            })
            pr["_matched"] = True # Flag to skip in Pass 2

    # --- PASS 2: NORMALIZED MATCH ---
    # For leftover invoices, look at the cleaned invoice numbers generated by M1.
    for pr in pr_list:
        if pr.get("_matched"):
            continue  # Already matched in Pass 1
            
        found_match = None
        for tx2b in portal_list:
            if tx2b["id"] in matched_portal_ids:
                continue
                
            # Normalized criteria match (using invoice_no_norm) 
            if (pr["supplier_gstin"] == tx2b["supplier_gstin"] and
                pr["invoice_no_norm"] == tx2b["invoice_no_norm"] and
                pr["invoice_date"] == tx2b["invoice_date"] and
                abs(pr["total_tax"] - tx2b["total_tax"]) < 0.01):
                
                found_match = tx2b
                break
                
        if found_match:
            matched_portal_ids.add(found_match["id"])
            match_results.append({
                "workspace_id": pr["workspace_id"],
                "client_id": pr["client_id"],
                "run_id": pr["run_id"],
                "purchase_invoice_id": pr["id"],
                "portal_invoice_id": found_match["id"],
                "bucket": "Matched",
                "match_pass": "P2_Normalized",
                "confidence": 95.0,
                "tax_diff": 0.0
            })
            pr["_matched"] = True

    # --- MISMATCHES & LEFTOVERS ---
    # Any PR invoice left over is flagged as Missing-in-Portal for the MVP[cite: 29, 56].
    for pr in pr_list:
        if not pr.get("_matched"):
            match_results.append({
                "workspace_id": pr["workspace_id"],
                "client_id": pr["client_id"],
                "run_id": pr["run_id"],
                "purchase_invoice_id": pr["id"],
                "portal_invoice_id": None,
                "bucket": "Missing-in-Portal",
                "match_pass": None,
                "confidence": 0.0,
                "tax_diff": pr["total_tax"]
            })

    return match_results